export const FONTS = {
  'epilogue': {
    name: 'Epilogue',
    family: ["Epilogue", "-apple-system", "BlinkMacSystemFont", "Avenir Next", "Avenir", "Segoe UI", "Helvetica Neue", "Adwaita Sans"," Cantarell", 'Ubuntu', "Roboto", "Noto", "Helvetica", "Arial", "sans-serif"],
    file: 'Epilogue.ttf',
    weight: '100 900',
    style: 'normal',
  },
  'gantari': {
    name: 'Gantari',
    family: ["Gantari", "-apple-system", "BlinkMacSystemFont", "Avenir Next", "Avenir", "Segoe UI", "Helvetica Neue", "Adwaita Sans"," Cantarell", 'Ubuntu', "Roboto", "Noto", "Helvetica", "Arial", "sans-serif"],
    file: "Gantari.ttf",
    weight: '100 900',
    style: 'normal',
  },
  'google-code': {
    name: "Google Sans Code",
    family: ["Google Sans Code", "Menlo", "Consolas", "Monaco", "Adwaita Mono", "Liberation Mono", "Lucida Console", "monospace"],
    file: "GoogleSansCode.ttf",
    weight: '300 800',
    style: 'normal',
  },
  'grandstander': {
    name: "Grandstander",
    family: ["Grandstander", "-apple-system", "BlinkMacSystemFont", "Avenir Next", "Avenir", "Segoe UI", "Helvetica Neue", "Adwaita Sans"," Cantarell", 'Ubuntu', "Roboto", "Noto", "Helvetica", "Arial", "sans-serif"],
    file: 'Grandstander.ttf',
    weight: '100 900',
    style: 'normal',
  },
  'karla': {
    name: "Karla",
    family: ["Karla", "-apple-system", "BlinkMacSystemFont", "Avenir Next", "Avenir", "Segoe UI", "Helvetica Neue", "Adwaita Sans"," Cantarell", 'Ubuntu', "Roboto", "Noto", "Helvetica", "Arial", "sans-serif"],
    file: "Karla.ttf",
    weight: '200 800',
    style: 'normal',
  },
  'libre-franklin': {
    name: "Libre Franklin",
    family: ["Libre Franklin", "-apple-system", "BlinkMacSystemFont", "Avenir Next", "Avenir", "Segoe UI", "Helvetica Neue", "Adwaita Sans"," Cantarell", 'Ubuntu', "Roboto", "Noto", "Helvetica", "Arial", "sans-serif"],
    file: "LibreFranklin.ttf",
    weight: '100 900',
    style: 'normal',
  },
  'lora': {
    name: "Lora",
    family: ["Lora", "Iowan Old Style", "Apple Garamond", "Baskerville", "Times New Roman", "Droid Serif", "Times", "Source Serif Pro", "serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"],
    file: "Lora.ttf",
    weight: '400 700',
    style: 'normal',
  },
  'newsreader': {
    name: "Newsreader",
    family: ["Newsreader","Iowan Old Style", "Apple Garamond", "Baskerville", "Times New Roman", "Droid Serif", "Times", "Source Serif Pro", "serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"],
    file: "Newsreader.ttf",
    weight: '200 800',
    style: 'normal',
  },
};